name: Full Test Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

env:
  NODE_VERSION: 'lts/*'

jobs:
  # Stage 1: Lint and Type Check
  lint-and-typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      - run: npm ci
      - run: npm run lint --if-present
      - run: npm run typecheck --if-present

  # Stage 2: Smoke Tests (Fast Feedback)
  smoke-tests:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    needs: [lint-and-typecheck]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      - run: npm ci
      - run: npx playwright install --with-deps chromium

      - name: Run smoke tests
        run: npx playwright test --grep @smoke --project=chromium
        env:
          CI: true

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: smoke-test-report
          path: playwright-report/
          retention-days: 7

  # Stage 3: Full Regression Tests (Multi-Browser)
  regression-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    needs: [smoke-tests]

    strategy:
      fail-fast: false
      matrix:
        project: [chromium, firefox, webkit]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      - run: npm ci
      - run: npx playwright install --with-deps ${{ matrix.project }}

      - name: Run regression tests (${{ matrix.project }})
        run: npx playwright test --grep @regression --project=${{ matrix.project }}
        env:
          CI: true

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: regression-report-${{ matrix.project }}
          path: playwright-report/
          retention-days: 7

  # Stage 3: Accessibility Tests (Parallel with Regression)
  accessibility-tests:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    needs: [smoke-tests]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      - run: npm ci
      - run: npx playwright install --with-deps chromium

      - name: Run accessibility tests
        run: npx playwright test --grep @a11y --project=chromium
        env:
          CI: true

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: a11y-report
          path: |
            playwright-report/
            a11y-reports/
          retention-days: 14

  # Stage 3: Visual Tests (Parallel with Regression)
  visual-tests:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    needs: [smoke-tests]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      - run: npm ci
      - run: npx playwright install --with-deps chromium

      - name: Run visual tests
        run: npx playwright test --grep @visual --project=chromium
        env:
          CI: true

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: visual-diff-report
          path: test-results/
          retention-days: 7

  # Stage 4: Report Summary
  report-summary:
    if: always()
    needs: [smoke-tests, regression-tests, accessibility-tests, visual-tests]
    runs-on: ubuntu-latest

    steps:
      - name: Generate summary
        run: |
          echo "## Test Results Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Test Suite | Status |" >> $GITHUB_STEP_SUMMARY
          echo "|------------|--------|" >> $GITHUB_STEP_SUMMARY
          echo "| Smoke Tests | ${{ needs.smoke-tests.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Regression Tests | ${{ needs.regression-tests.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Accessibility Tests | ${{ needs.accessibility-tests.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Visual Tests | ${{ needs.visual-tests.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Artifacts" >> $GITHUB_STEP_SUMMARY
          echo "Download test reports from the Actions tab artifacts section." >> $GITHUB_STEP_SUMMARY

      - name: Check for failures
        if: contains(needs.*.result, 'failure')
        run: |
          echo "One or more test suites failed!"
          exit 1
