name: Visual Regression Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  visual-tests:
    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium

      - name: Run Visual Regression Tests
        run: npx playwright test --project=chromium tests/visual/
        env:
          CI: true

      - name: Upload Visual Diff Report
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: visual-diff-report
          path: |
            playwright-report/
            test-results/
          retention-days: 7

      - name: Comment on PR with visual diff
        if: failure() && github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '## Visual Regression Test Failed\n\nVisual differences detected. Please review the visual diff in the [workflow artifacts](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}).\n\nIf the changes are intentional, update the baselines with:\n```bash\nnpx playwright test --update-snapshots\n```'
            })

  update-baselines:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium

      - name: Update baseline screenshots
        run: npx playwright test --project=chromium tests/visual/ --update-snapshots
        env:
          CI: true

      - name: Commit updated baselines
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add "**/*.png"
          git diff --staged --quiet || git commit -m "chore: update visual baseline screenshots [skip ci]"
          git push
